# Generated by Django 5.0.7 on 2024-07-16 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generate_molecules', '0030_rename_lipinski_violations_generatedmolecule_lipinskis_violations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('report_name', models.CharField(max_length=1000)),
                ('include_smile_identifier', models.BooleanField(default=True)),
                ('include_molecular_structure', models.BooleanField(default=True)),
                ('include_molecular_formula', models.BooleanField(default=True)),
                ('include_molecular_weight', models.BooleanField(default=True)),
                ('include_H_bond_acceptors', models.BooleanField(default=True)),
                ('include_H_bond_donors', models.BooleanField(default=True)),
                ('include_heavy_atoms', models.BooleanField(default=True)),
                ('include_rotatable_bonds', models.BooleanField(default=True)),
                ('include_lipinskis_violations', models.BooleanField(default=True)),
                ('include_synthetic_accessibility_score', models.DecimalField(decimal_places=3, max_digits=100)),
                ('molecules', models.ManyToManyField(blank=True, null=True, to='generate_molecules.generatedmolecule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
