# Generated by Django 5.0.7 on 2024-07-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='include_synthetic_accessibility_score',
            field=models.IntegerField(default=True),
        ),
    ]
