# Generated by Django 5.0.7 on 2024-07-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_include_synthetic_accessibility_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='include_synthetic_accessibility_score',
        ),
    ]
