# Generated by Django 5.0.7 on 2024-07-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_include_synthetic_accessibility_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='include_synthetic_accessibility_score',
            field=models.BooleanField(default=True),
        ),
    ]
