# Generated by Django 5.0.7 on 2024-07-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_include_synthetic_accessibility_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='include_H_bond_acceptors',
        ),
        migrations.RemoveField(
            model_name='report',
            name='include_H_bond_donors',
        ),
        migrations.RemoveField(
            model_name='report',
            name='include_heavy_atoms',
        ),
        migrations.RemoveField(
            model_name='report',
            name='include_lipinskis_violations',
        ),
        migrations.RemoveField(
            model_name='report',
            name='include_molecular_formula',
        ),
        migrations.RemoveField(
            model_name='report',
            name='include_molecular_structure',
        ),
        migrations.RemoveField(
            model_name='report',
            name='include_molecular_weight',
        ),
        migrations.RemoveField(
            model_name='report',
            name='include_rotatable_bonds',
        ),
        migrations.RemoveField(
            model_name='report',
            name='include_smile_identifier',
        ),
        migrations.RemoveField(
            model_name='report',
            name='include_synthetic_accessibility_score',
        ),
    ]
