# Generated by Django 5.0.7 on 2024-07-16 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_report_include_h_bond_acceptors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
