# Generated by Django 5.0.6 on 2024-07-06 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('type_of_request', models.CharField(choices=[('target', 'target'), ('from_compounds', 'from_compounds')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreatedMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smile_identifier', models.CharField(max_length=1000)),
                ('molecular_structure', models.ImageField(upload_to='molecular_structures/')),
                ('generation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_molecules.generationrequest')),
            ],
        ),
    ]
