# Generated by Django 5.0.6 on 2024-07-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreatedMolecule',
            new_name='GeneratedMolecule',
        ),
    ]
