# Generated by Django 5.0.6 on 2024-07-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0002_rename_createdmolecule_generatedmolecule'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
