# Generated by Django 5.0.6 on 2024-07-06 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0003_generationrequest_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
