# Generated by Django 5.0.6 on 2024-07-07 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0004_generationrequest_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromCompounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FromTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='type_of_request',
            field=models.CharField(choices=[('from_target', 'from_target'), ('from_compounds', 'from_compounds')], max_length=100),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='from_compounds',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generate_molecules.fromcompounds'),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='from_target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generate_molecules.fromtarget'),
        ),
    ]
