# Generated by Django 5.0.6 on 2024-07-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0006_generatedmolecule_synthetic_accessibility_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generationrequest',
            old_name='from_compounds',
            new_name='from_molecules',
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='type_of_request',
            field=models.CharField(choices=[('from_target', 'from_target'), ('from_molecules', 'from_molecules')], max_length=100),
        ),
    ]
