# Generated by Django 5.0.6 on 2024-07-08 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0007_rename_from_compounds_generationrequest_from_molecules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FromMolecules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecules_plain_text', models.CharField(blank=True, max_length=1000000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='from_molecules',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generate_molecules.frommolecules'),
        ),
        migrations.DeleteModel(
            name='FromCompounds',
        ),
    ]
