# Generated by Django 5.0.7 on 2024-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0008_frommolecules_alter_generationrequest_from_molecules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationrequest',
            name='from_molecules',
        ),
        migrations.RemoveField(
            model_name='generationrequest',
            name='from_target',
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='molecules_plain_text',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.DeleteModel(
            name='FromMolecules',
        ),
        migrations.DeleteModel(
            name='FromTarget',
        ),
    ]
