# Generated by Django 5.0.7 on 2024-07-09 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0010_disease_organism_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='model',
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='greater_than_cutoff',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='standard_value_cutoff',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generate_molecules.target'),
        ),
        migrations.AddField(
            model_name='target',
            name='default_greater_than_cutoff',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='default_standard_value_cutoff',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='standard_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='standard_units',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='training_data',
            field=models.FileField(blank=True, null=True, upload_to='target_data/'),
        ),
    ]
