# Generated by Django 5.0.7 on 2024-07-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0011_remove_target_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='organism',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generate_molecules.organism'),
            preserve_default=False,
        ),
    ]
