# Generated by Django 5.0.7 on 2024-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0012_alter_target_organism'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='chembl_id',
            field=models.CharField(default="N/A", max_length=1000),
            preserve_default=False,
        ),
    ]
