# Generated by Django 5.0.7 on 2024-07-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0015_generationrequest_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='default_greater_than_cutoff',
        ),
        migrations.AddField(
            model_name='target',
            name='default_comparator',
            field=models.CharField(choices=[('less than', 'less than'), ('greater than', 'greater than'), ('less than or equal to', 'less than or equal to'), ('greater than or equal to', 'greater than or equal to')], default='less than or equal to', max_length=1000),
        ),
    ]
