# Generated by Django 5.0.7 on 2024-07-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0016_remove_target_default_greater_than_cutoff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationrequest',
            name='greater_than_cutoff',
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='comparator',
            field=models.CharField(blank=True, choices=[('less than', 'less than'), ('greater than', 'greater than'), ('less than or equal to', 'less than or equal to'), ('greater than or equal to', 'greater than or equal to')], max_length=1000, null=True),
        ),
    ]
