# Generated by Django 5.0.7 on 2024-07-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0017_remove_generationrequest_greater_than_cutoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='molecules_ai_trained_on',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='comparator',
            field=models.CharField(blank=True, choices=[('less_than', 'less_than'), ('greater_than', 'greater_than'), ('less_than_or_equal_to', 'less_than_or_equal_to'), ('greater_than_or_equal_to', 'greater_than_or_equal_to')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='default_comparator',
            field=models.CharField(choices=[('less_than', 'less_than'), ('greater_than', 'greater_than'), ('less_than_or_equal_to', 'less_than_or_equal_to'), ('greater_than_or_equal_to', 'greater_than_or_equal_to')], default='less_than_or_equal_to', max_length=1000),
        ),
    ]
