# Generated by Django 5.0.7 on 2024-07-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0018_generationrequest_molecules_ai_trained_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='time_completed_creating',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='time_started_creating',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='standard_value_cutoff',
            field=models.FloatField(blank=True, max_length=1000, null=True),
        ),
    ]
