# Generated by Django 5.0.7 on 2024-07-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0019_generationrequest_time_completed_creating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrequest',
            name='molecules_plain_text',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
