# Generated by Django 5.0.7 on 2024-07-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0020_alter_generationrequest_molecules_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='training_data',
            field=models.FileField(blank=True, null=True, upload_to='target_data/training_data/'),
        ),
    ]
