# Generated by Django 5.0.7 on 2024-07-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0021_alter_target_training_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmolecule',
            name='H_bond_acceptors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedmolecule',
            name='H_bond_donors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedmolecule',
            name='chemical_formula',
            field=models.CharField(default='error', max_length=1000),
        ),
        migrations.AddField(
            model_name='generatedmolecule',
            name='molecular_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='generatedmolecule',
            name='rotatable_bonds',
            field=models.IntegerField(default=0),
        ),
    ]
