# Generated by Django 5.0.7 on 2024-07-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0022_generatedmolecule_h_bond_acceptors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedmolecule',
            old_name='chemical_formula',
            new_name='molecular_formula',
        ),
    ]
