# Generated by Django 5.0.7 on 2024-07-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0023_rename_chemical_formula_generatedmolecule_molecular_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmolecule',
            name='heavy_atoms',
            field=models.IntegerField(default=0),
        ),
    ]
