# Generated by Django 5.0.7 on 2024-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0024_generatedmolecule_heavy_atoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmolecule',
            name='logp',
            field=models.FloatField(default=0),
        ),
    ]
