# Generated by Django 5.0.7 on 2024-07-15 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0026_generationrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmolecule',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
