# Generated by Django 5.0.7 on 2024-07-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0027_generatedmolecule_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmolecule',
            name='violations',
            field=models.IntegerField(default=0),
        ),
    ]
