# Generated by Django 5.0.7 on 2024-07-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0028_generatedmolecule_violations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedmolecule',
            old_name='violations',
            new_name='lipinski_violations',
        ),
    ]
