# Generated by Django 5.0.7 on 2024-07-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0029_rename_violations_generatedmolecule_lipinski_violations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedmolecule',
            old_name='lipinski_violations',
            new_name='lipinskis_violations',
        ),
    ]
