# Generated by Django 5.0.7 on 2024-07-16 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0030_rename_lipinski_violations_generatedmolecule_lipinskis_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmolecule',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
