# Generated by Django 5.0.7 on 2024-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_molecules', '0031_generatedmolecule_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
